version: '3.8'

services:
  ragapp:
    build: .
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=RAG
    env_file:
      - .env  # Load additional environment variables
    restart: unless-stopped  # Restart container if it crashes
